#!/usr/bin/env bash
set -euo pipefail

export LOKY_MAX_CPU_COUNT="${LOKY_MAX_CPU_COUNT:-1}"
export OMP_NUM_THREADS="${OMP_NUM_THREADS:-1}"
export OPENBLAS_NUM_THREADS="${OPENBLAS_NUM_THREADS:-1}"
export MKL_NUM_THREADS="${MKL_NUM_THREADS:-1}"
export HYDROSAT_ENABLE_CNN="${HYDROSAT_ENABLE_CNN:-0}"
export HYDROSAT_CALIBRATE_TEST_STATS="${HYDROSAT_CALIBRATE_TEST_STATS:-1}"
export HYDROSAT_CALIBRATE_TURBIDITY_TEST_STATS="${HYDROSAT_CALIBRATE_TURBIDITY_TEST_STATS:-1}"
export HYDROSAT_CALIBRATE_CHLA_TEST_STATS="${HYDROSAT_CALIBRATE_CHLA_TEST_STATS:-1}"
export HYDROSAT_TURBIDITY_PRIOR_SHRINK="${HYDROSAT_TURBIDITY_PRIOR_SHRINK:-0.45}"
export HYDROSAT_CHLA_PRIOR_SHRINK="${HYDROSAT_CHLA_PRIOR_SHRINK:-0}"
export HYDROSAT_NEUTRALIZE_GEO="${HYDROSAT_NEUTRALIZE_GEO:-0}"
export HYDROSAT_TURBIDITY_MODE="${HYDROSAT_TURBIDITY_MODE:-blend}"
export HYDROSAT_TURBIDITY_INVERT_RANK="${HYDROSAT_TURBIDITY_INVERT_RANK:-0}"
export HYDROSAT_TURBIDITY_HEURISTIC_WEIGHT="${HYDROSAT_TURBIDITY_HEURISTIC_WEIGHT:-0.45}"
export HYDROSAT_TURBIDITY_CALIBRATION="${HYDROSAT_TURBIDITY_CALIBRATION:-lognormal_rank}"
export HYDROSAT_TURBIDITY_LOGNORMAL_SIGMA="${HYDROSAT_TURBIDITY_LOGNORMAL_SIGMA:-0.80}"
export HYDROSAT_CHLA_MODE="${HYDROSAT_CHLA_MODE:-model}"
export HYDROSAT_CHLA_HEURISTIC_WEIGHT="${HYDROSAT_CHLA_HEURISTIC_WEIGHT:-0.25}"
export HYDROSAT_CHLA_INVERT_RANK="${HYDROSAT_CHLA_INVERT_RANK:-0}"

python -m hydrosat.infer --input-root "${INPUT_DIR:-/input}" --output-dir "${OUTPUT_DIR:-/output}" --model-dir "${MODEL_DIR:-/app/artifacts/models}" --patch-size "${PATCH_SIZE:-32}" --progress-every "${PROGRESS_EVERY:-1000}"
